name: arc-runner-set
on:
  workflow_dispatch:


  schedule:
    - cron: '*/5 * * * *' 

jobs:
  download:
    runs-on: repo-runner
    steps:
      - name: Sleep
        run: |
          echo "hello"
          ls
